# Generated by Django 3.1.1 on 2020-09-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0002_auto_20200907_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_name',
        ),
    ]
